// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "LTime API": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/lvikstro/ltime/backend/design
// --out=$(GOPATH)/src/github.com/lvikstro/ltime/backend
// --version=v1.3.1

package test
